version: '3'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db
    networks:
      - my_network
    ports:
      - "5432:5432"
  
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ecommerce_db
      DJANGO_SECRET_KEY: your_django_secret_key
      DEBUG: 'True'
      # Add other environment variables for Django, such as:
      # DJANGO_ALLOWED_HOSTS, DATABASE_URL, etc.
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
