name: Django CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up PostgreSQL container (if not CI)
        run: |
          docker-compose -f docker-compose.yml up -d postgres

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (Skip PostgreSQL tests)
        run: |
          echo "Skipping PostgreSQL tests"
          # Run tests that don't rely on PostgreSQL here
          python manage.py test --exclude-tag=postgresql  # Example for excluding PostgreSQL tests

      - name: Run tests if not in CI (optional step for local)
        run: |
          docker-compose exec -T web python manage.py test  # Run tests with PostgreSQL

  teardown:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check Docker Compose services status
        run: docker-compose ps

      - name: Capture Docker Compose logs
        run: docker-compose logs

      - name: Shutdown PostgreSQL container
        run: |
          docker-compose down
